source "http://rubygems.org"

gem 'jekyll', '~>1.0'
gem '<%= jekMkd %>'
gem 'csscss', '~>1.3'
gem 'sass', '>=3.2'
gem 'compass', '>=0.12'
gem 'archetype-utilities', '>=0.1.0'
gem 'colorkit', '>=0.4.7'
gem 'modular-scale', '>=0.0.4'
gem 'breakpoint', '>=2.0.6'
